language: python
python:
  - '3.7'
deploy:
  provider: pypi
  user: sparshik
  password:
    secure: $PYPI_PASSWORD
  server: https://mypackageindex.com/index
  distributions: "sdist bdist_wheel" # Your distributions here

  on:
    branch: master