language: python
python:
  - '3.7'
script:
  - echo foo
deploy:
  provider: pypi
  user: __token__
  password: $PYPI_TOKEN
  server: https://test.pypi.org/legacy/
  distributions: "sdist bdist_wheel" # Your distributions here
  on:
    branch: master